project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "FEF1002 Introduction to Basic Computer Technologies"
  navbar:
    left:
      - href: index.qmd
        text: Main
      - href: about.qmd
        text: About
format:
  html:
    theme: cosmo
    #css: styles.css
    toc: true
