# FEF1002 Introduction to Basic Computer Technologies

## Resources

- The lecture materials will be provided at this website

## Lecture1

*October 1st, 2024, Tuesday 4-7pm, ONLINE*

**Contents**: Introduction about the lecture

## Lecture2

*October 8th, 2024, Tuesday 4-7pm, ONLINE*

**Contents**: Latex [link for lecture materials](latex-lecture1-en.ipynb)

## Lecture3

*October 15th, 2024, Tuesday 4-7pm, ONLINE*

**Contents**: Latex at Overleaf [link for lecture materials](latex-lecture2-en.ipynb)

## Lecture4

*October 22th, 2024, Tuesday 4-7pm, ONLINE*

**Contents**: Introduction to algoritms [link for lecture material](week4-algoritms-en.qmd) and Excel [link for lecture material](week4-excel-en.qmd)

## Lecture5

*November 5th, 2024, Tuesday 4-7pm, ONLINE*

**Contents**: Excel Part2 [link for lecture material](week5-excel-part2.qmd)

## Lecture6

*November 12th, 2024, Tuesday 4-7pm, ONLINE*

**Contents**: Excel Pivot tables and charts [link for lecture material](week6-excel-part3.qmd)

## Lecture7

*November 26th, 2024, Tuesday 4-7pm, ONLINE*

**Contents**: Python part1 [link for lecture material](fef1002-python.ipynb)

## Lecture8

*December 3rd, 2024, Tuesday 4-7pm, ONLINE*

**Contents**: Python part2 [link for lecture material](fef1002-pythonB.ipynb)

## Lecture9

*December 10th, 2024, Tuesday 4-7pm, ONLINE*

**Contents**: SPSS Part1 [link for lecture material](1_SPSS.ipynb), [html_version](1_SPSS_htmlversion.html). Derste kullanılan dosyalar: [mtcars.sav](files/mtcars.sav), [hs0.sav](files/hs0.sav)

## Lecture10

*December 17th, 2024, Tuesday 4-7pm, ONLINE*

**Contents**: SPSS Part2 [link for lecture material](2_SPSS.ipynb), [html_version](2_SPSS_htmlversion.html). Derste kullanılan dosyalar: [mtcars.sav](files/mtcars.sav), [hs0.sav](files/hs0.sav)

## Lecture11

*December 24th, 2024, Tuesday 4-7pm, ONLINE*

**Contents**: R language 1 [link for lecture material](r_week1_en.ipynb), [html_version](r_week1_en_html.html). Derste kullanılan dosyalar: [pima.csv](files/pima.csv), [pima.dat](files/pima.dat), [pima.db](files/pima.db), [pima.xls](files/pima.xls), [pima.xlsx](files/pima.xlsx)

## Lecture12

*January 7th, 2025  Tuesday 4-7pm, ONLINE*

**Contents**: R language part 2 [link for lecture material](r_week2_en.ipynb), [html_version](r_week2_en_html.html).
